export type {
  Property,
  PropertyBadge,
  PropertyFeature,
  PropertyFilters,
  PropertySort,
  InquiryInput,
  Inquiry,
  ReservationNotification,
  CreatePropertyFormInput,
  UpdatePropertyFormInput,
  SiteSettings,
  UpdateSiteSettingsInput,
} from "./api";

export {
  fetchProperties,
  fetchRecentProperties,
  fetchCondominiums,
  fetchPropertyBySlug,
  fetchSimilarProperties,
  fetchInquiries,
  submitInquiry,
  deleteInquiry,
  fetchNotificationCount,
  fetchUnreadInquiries,
  postNotification,
  markNotificationsRead,
  createProperty,
  updateProperty,
  deleteProperty,
  fetchSiteSettings,
  verifyAdminLogin,
  updateSiteSettings,
  resolveMediaUrl,
  getApiOrigin,
} from "./api";
